name: VitalSkull
version: @version@
main: dev.meinel.leo.vitalskull.VitalSkull
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives players the ability to get their own skull.
commands:
  skull:
    description: "Main command"
    usage: "/skull"
permissions:
  vitalskull.skull:
    description: "Permission to get your own head"
    default: op
  vitalskull.cooldown.bypass:
    description: "Permission to bypass cooldown"
    default: op